import { FilterMode } from "./modeOptions";

export const ColumnType = Object.freeze({
  DTO: "dto",
  Text: "text",
  Date: "date",
  Datetime: "datetime",
  Boolean: "boolean",
  Number: "number",
  Numeric: "numeric",
  Amount: "amount",
  Rate: "rate",
  DOC: "doc",
  //TODO to be refactor
  Actions: "actions",
  Icon: "icon",
  ProductIcon: "productIcon",
  SignIcon: "signIcon",
  CheckboxIcon: "checkboxIcon",
  Checked: "checked",
  Button: "button",
  Link: "Link",
  BADGE: "badge",
  Switch: "switch",
  PERCENT: "percent",
  Lookup: "lookup",
  CompactNumber: "compactNumber",
  Price: "price",
  CompactPrice: "compactPrice",
  PurchaseType: "purchaseType",
  RemoveAction: "removeAction",
});

export const ColumnTypeModes: any = Object.freeze({
  [ColumnType.DTO]: [
    FilterMode.IncludesSome,
    FilterMode.Equals,
    // FilterMode.NotEquals,
  ],
  [ColumnType.Text]: [
    FilterMode.Contains,
    FilterMode.StartsWith,
    FilterMode.EndsWith,
    FilterMode.Equals,
    // FilterMode.NotEquals,
    // FilterMode.Empty,
    // FilterMode.NotEmpty,
  ],
  [ColumnType.Date]: [
    FilterMode.Between,
    FilterMode.BetweenInclusive,
    FilterMode.GreaterThan,
    FilterMode.GreaterThanOrEqualTo,
    FilterMode.LessThan,
    FilterMode.LessThanOrEqualTo,
    FilterMode.Equals,
    // FilterMode.NotEquals,
    // FilterMode.Empty,
    // FilterMode.NotEmpty,
  ],
  [ColumnType.Boolean]: [
    FilterMode.Equals,
    // FilterMode.NotEquals,
    // FilterMode.Empty,
    // FilterMode.NotEmpty,
  ],
  [ColumnType.Number]: [
    FilterMode.Between,
    FilterMode.BetweenInclusive,
    FilterMode.GreaterThan,
    FilterMode.GreaterThanOrEqualTo,
    FilterMode.LessThan,
    FilterMode.LessThanOrEqualTo,
    FilterMode.Equals,
    // FilterMode.NotEquals,
    // FilterMode.Empty,
    // FilterMode.NotEmpty,
  ],
  [ColumnType.Numeric]: [
    FilterMode.Between,
    FilterMode.BetweenInclusive,
    FilterMode.GreaterThan,
    FilterMode.GreaterThanOrEqualTo,
    FilterMode.LessThan,
    FilterMode.LessThanOrEqualTo,
    FilterMode.Equals,
    // FilterMode.NotEquals,
    // FilterMode.Empty,
    // FilterMode.NotEmpty,
  ],
  [ColumnType.Amount]: [
    FilterMode.Between,
    FilterMode.BetweenInclusive,
    FilterMode.GreaterThan,
    FilterMode.GreaterThanOrEqualTo,
    FilterMode.LessThan,
    FilterMode.LessThanOrEqualTo,
    FilterMode.Equals,
    // FilterMode.NotEquals,
    // FilterMode.Empty,
    // FilterMode.NotEmpty,
  ],
  [ColumnType.Rate]: [
    FilterMode.Between,
    FilterMode.BetweenInclusive,
    FilterMode.GreaterThan,
    FilterMode.GreaterThanOrEqualTo,
    FilterMode.LessThan,
    FilterMode.LessThanOrEqualTo,
    FilterMode.Equals,
    // FilterMode.NotEquals,
    // FilterMode.Empty,
    // FilterMode.NotEmpty,
  ],
  [ColumnType.DOC]: [
    FilterMode.Equals,
    // FilterMode.NotEquals,
    // FilterMode.Empty,
    // FilterMode.NotEmpty,
  ],
});
