export const FilterMode = Object.freeze({
  Between: "between",
  BetweenInclusive: "betweenInclusive",
  Contains: "contains",
  Empty: "empty",
  NotEmpty: "notEmpty",
  StartsWith: "startsWith",
  EndsWith: "endsWith",
  Equals: "equals",
  NotEquals: "notEquals",
  GreaterThan: "greaterThan",
  GreaterThanOrEqualTo: "greaterThanOrEqualTo",
  LessThan: "lessThan",
  LessThanOrEqualTo: "lessThanOrEqualTo",
  IncludesSome: "arrIncludesSome",
});

export const modeOptions = [
  { code: FilterMode.Equals, label: "Equals", isMultiple: false, symbol: "=" },
  {
    code: FilterMode.NotEquals,
    label: "Not Equals",
    isMultiple: false,
    symbol: "≠",
  },
  {
    code: FilterMode.Contains,
    label: "Contains",
    isMultiple: false,
    symbol: "*",
  },
  {
    code: FilterMode.StartsWith,
    label: "Starts With",
    isMultiple: false,
    symbol: "a",
  },
  {
    code: FilterMode.EndsWith,
    label: "EndsWith",
    isMultiple: false,
    symbol: "z",
  },
  {
    code: FilterMode.GreaterThan,
    label: "Greater Than",
    isMultiple: false,
    symbol: ">",
  },
  {
    code: FilterMode.GreaterThanOrEqualTo,
    label: "Greater Than Or Equal To",
    isMultiple: false,
    symbol: "≥",
  },
  {
    code: FilterMode.LessThan,
    label: "Less Than",
    isMultiple: false,
    symbol: "<",
  },
  {
    code: FilterMode.LessThanOrEqualTo,
    label: "Less Than Or Equal To",
    symbol: "≤",
    isMultiple: false,
  },
  { code: FilterMode.Between, label: "Between", isMultiple: true, symbol: "⇿" },
  {
    code: FilterMode.BetweenInclusive,
    label: "Between Inclusive",
    isMultiple: true,
    symbol: "⬌",
  },
  {
    code: FilterMode.IncludesSome,
    label: "Includes",
    isMultiple: true,
    symbol: "in",
  },
  { code: FilterMode.Empty, label: "Empty", isMultiple: false, symbol: "∅" },
  {
    code: FilterMode.NotEmpty,
    label: "Not Empty",
    isMultiple: false,
    symbol: "!∅",
  },
  ////
  // { code: "includesString", label: "Includes String", isMultiple: false },
  // {
  //   code: "includesStringSensitive",
  //   label: "Includes String Sensitive",
  //   isMultiple: false,
  // },
  // { code: "equalsString", label: "Equals String", isMultiple: false },
  // { code: "arrIncludes", label: "Array Includes", isMultiple: true },
  // { code: "arrIncludesAll", label: "Array Includes All", isMultiple: true },
  // { code: "arrIncludesSome", label: "Array Includes Some", isMultiple: true },
  // { code: "inNumberRange", label: "In Number Range", isMultiple: true },
];
