export const RoutePath = {
  DASHBOARD: "/",
  SEARCH_RESULTS: "/search/results",
  TIER: "/tier",
  TIER_LIST: "/tier/list",
  TIER_VIEW: "/tier/view",
  TIER_NEW: "/tier/new",
  TIER_EDIT: "/tier/edit",
  TIER_HISTORY_LIST: "/tier/history",
  TIER_HISTORY_VIEW: "/tier/history/view",
  TIER_APPETITE_LIST: "/tier/appetite",
  TIER_LEGACY: "/legacy",
  TIER_LEGACY_LIST: "/legacy/list",
  TIER_LEGACY_VIEW: "/legacy/view",
  TIER_LEGACY_EDIT: "/legacy/edit",
  // HISTORY: "/history",
  // HISTORY_LIST: "/history/list",
  // HISTORY_VIEW: "/history/view",
  ANNOTATION: "/annotation",
  ANNOTATION_LIST: "/annotation/list",
  POLICY: "/policy",
  POLICY_LIST: "/policy/list",
  POLICY_EDIT: "/policy/edit",
  POLICY_VIEW: "/policy/view",
  POLICY_HISTORY_LIST: "/policy/history",
};
