import React from "react";
import messages from "config/i18n/messages";
import { PersonOutlined as PersonOutlinedIcon } from "@mui/icons-material";
import { CardWrapper, ViewField } from "components";

const ViewRejectedPhysical = ({ data }: { data: any }) => {
  return (
    <CardWrapper
      containerProps={{ spacing: 1 }}
      title={messages.maritalStatus}
      icon={PersonOutlinedIcon}
      collapsable
    >
      <ViewField
        direction="row"
        label={messages.city}
        value={data?.ville}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.country}
        value={data?.pays}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.sector}
        value={data?.secteur}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.vip}
        value={data?.vip}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.segment}
        value={data?.codeSegment}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.status}
        value={data?.statut}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.manager}
        value={data?.responsable}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.titleCivility}
        value={data?.titre}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.firstName}
        value={data?.prenom}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.lastName}
        value={data?.nom}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.dateOfBirth}
        value={data?.dateNaissance}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.placeOfBirth}
        value={data?.lieuNaissance}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.gender}
        value={data?.sexe}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.familySituation}
        value={data?.situationFamille}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.nationality}
        value={data?.nationalite}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.profession}
        value={data?.profession}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.countryOfBirth}
        value={data?.paysNaissance}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.cityOfBirth}
        value={data?.villeNaissance}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.registrationNumber}
        value={data?.matricule}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.numberOfChildren}
        value={data?.nbrEnfant}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.dateDeath}
        value={data?.dateDeces}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.deathStatus}
        value={data?.statutDeces}
        xs={4}
      />
      <ViewField
        direction="row"
        label={messages.segmentScore}
        value={data?.segScore}
        xs={4}
      />
    </CardWrapper>
  );
};

export default ViewRejectedPhysical;
